=== hholgersen/tap-prefect/tap_prefect/schemas/task_runs.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "updated": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "flow_id": {
            "type": "string"
        },
        "state_id": {
            "type": "string"
        },
        "deployment_id": {
            "type": "string"
        },
        "work_queue_name": {
            "type": "string"
        },
        "flow_version": {
            "type": "string"
        },
        "parameters": {
            "type": "object"
        },
        "idempotency_key": {
            "type": "string"
        },
        "context": {
            "type": "object"
        },
        "empirical_policy": {
            "type": "object"
        },
        "tags": {
            "type": "array"
        },
        "parent_task_run_id": {
            "type": "string"
        },
        "state_type": {
            "type": "string"
        },
        "state_name": {
            "type": "string"
        },
        "run_count": {
            "type": "integer"
        },
        "expected_start_time": {
            "type": "string"
        },
        "next_scheduled_start_time": {
            "type": [
                "null",
                "string"
            ]
        },
        "start_time": {
            "type": "string"
        },
        "end_time": {
            "type": "string"
        },
        "total_run_time": {
            "type": "number"
        },
        "estimated_run_time": {
            "type": "number"
        },
        "estimated_start_time_delta": {
            "type": [
                "null",
                "number"
            ]
        },
        "auto_scheduled": {
            "type": "boolean"
        },
        "infrastructure_document_id": {
            "type": "string"
        },
        "infrastructure_pid": {
            "type": "string"
        },
        "created_by": {
            "type": "object"
        },
        "work_pool_name": {
            "type": "string"
        },
        "state": {
            "type": "object"
        }
    }
}

=== hholgersen/tap-prefect/tests/sample_responses/flows.json
[
  {
    "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
    "created": "2019-08-24T14:15:22Z",
    "updated": "2019-08-24T14:15:22Z",
    "name": "my-flow",
    "tags": [
        "tag-1",
        "tag-2"
    ]
  },
  {
    "id": "507f6eca-6276-4993-bfeb-53cbbbba6f09",
    "created": "2019-08-24T14:15:22Z",
    "updated": "2019-08-24T14:15:22Z",
    "name": "my-other-flow",
    "tags": [
        "tag-1",
        "tag-2"
    ]
  }
]
